name: CI Workflow

on:
  push:
    branches:
      - main
      - release
      - feat/tests
  pull_request:
    branches:
      - master
      - release
      - develop
      - feat/tests

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Шаг 1: Вывод ФИО, номера группы и ника на Github
    - name: Output personal information
      run: |
        echo "Full Name: Иванов Иван Иванович"
        echo "Group Number: 12345"
        echo "GitHub Username: ${{ github.actor }}"

    - name: checkout
      uses: action/checkout@v3
      
    # Шаг 2: Установка Python 3.13
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Шаг 3: Установка зависимостей из requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Шаг 4: Запуск тестов с использованием Test Discovery
    - name: Run tests
      run: |
        python -m unittest discover -s tests

    # Шаг 5: Проверка стиля кода с использованием flake8
    - name: Check code style with flake8
      run: |
        pip install flake8
        flake8 .
